### ISSUE TITLE
When the application starts don't render renderer.js

### ISSUE THREAD

**Issue by HashimotoYT** [siberianmh/gitburn#22]
### Description

When the application starts:
`Failed to load resource: net::ERR_CONNECTION_REFUSED` in renderer.js

Screenshot:
![default](https://user-images.githubusercontent.com/24681191/27618643-3163f13c-5bc6-11e7-8ace-f6a1ad61c9e8.png)

### Version

**GitBurn version:** Development build 6a4b495084f23b7e18abfcf31c7d4a5bb29bb940

**OS version:** Microsoft Windows [Version 10.0.15063]

**Comment by HashimotoYT** [comment]
After commit: 7248b37266497af12001f7323ba12c386ef9825d

```
Invariant Violation: Minified React error #37; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=37 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at R.exports (app\~\react-dom\lib\reactProdInvariant.js:31:1)
    at Object._renderNewRootComponent (app\~\react-dom\lib\ReactMount.js:305:1)
    at Object._renderSubtreeIntoContainer (app\~\react-dom\lib\ReactMount.js:377:1)
    at Object.render (app\~\react-dom\lib\ReactMount.js:402:1)
    at Object.<anonymous> (app\src\ui\index.tsx:124:16)
    at I (E:\Development\gitburn\dist\GitBurn-win32-x64\webpack:\webpack\bootstrap c2360cfdb2aa3afe6407:9:1)
    at E:\Development\gitburn\dist\GitBurn-win32-x64\webpack:\webpack\bootstrap c2360cfdb2aa3afe6407:59:1
    at E:\Development\gitburn\dist\GitBurn-win32-x64\webpack:\webpack\bootstrap c2360cfdb2aa3afe6407:59:55

Version: 0.0.1
OS: Windows 10.0.15063
```
